CREATE DATABASE `world` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE `characters` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE `accounts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'JMaNGOS'@'localhost' IDENTIFIED BY 'JMaNGOS';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON `world`.* TO 'JMaNGOS'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON `characters`.* TO 'JMaNGOS'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON `accounts`.* TO 'JMaNGOS'@'localhost';

FLUSH PRIVILEGES;